apiVersion: v1
kind: Pod
metadata:
  name: suspicious-pod
  namespace: default
spec:
  hostNetwork: true
  containers:
    - name: app
      image: nginx:latest
      volumeMounts:
        - name: etc
          mountPath: /tmp/etc
  volumes:
    - name: etc
      hostPath:
        path: /etc
        type: DirectoryOrCreate