apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
          cpu: "100m"
        limits:
          memory: "100Mi" # This is a tight limit!
          cpu: "200m"
      # This command tells the container to try and use 150MB of RAM
      # Since our limit is 100Mi, it WILL fail.
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
